### ISSUE TITLE
ApiResponse isn't HTTP agnostic

### ISSUE THREAD

**Issue by kelunik** [eole-io/sandstone-edition#1]
The `README` says:

> Using ApiResponse allows to make your controller return a HTTP-agnostic object

But `return new ApiResponse($result, Response::HTTP_OK);` shows a tight coupling to HTTP status codes.

**Comment by alcalyn** [comment]
Yes, true. It was ambitious to say it !

It's more a serialization-agnostic response as the need was to serialize it at the very end, or even allow to modify the response before serialization and sending (i.e from a listener).

**Comment by alcalyn** [comment]
Updated the doc. Thank you !
